### ISSUE TITLE
panic on smtp.Close()

### ISSUE THREAD

**Issue by smancke** [smancke/mailck#6]
```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x591822]

goroutine 152 [running]:
net/smtp.(*Client).Close(0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/smtp/smtp.go:75 +0x22
panic(0x74dce0, 0xb40a70)
        /home/travis/.gimme/versions/go/src/runtime/panic.go:489 +0x25b
net/smtp.(*Client).hello(0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/smtp/smtp.go:80 +0x26
net/smtp.(*Client).Quit(0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/smtp/smtp.go:382 +0x2f
panic(0x74dce0, 0xb40a70)
        /home/travis/.gimme/versions/go/src/runtime/panic.go:489 +0x25b
net/smtp.(*Client).Hello(0x0, 0xc42001601b, 0x9, 0x9, 0x0)
        /home/travis/.gimme/versions/go/src/net/smtp/smtp.go:96 +0x26
github.com/smancke/mailck.checkMailbox.func1(0x0, 0xc420252bb0, 0xc420016013, 0x11, 0xc420235c20, 0xc420252610, 0xc)
        /home/travis/gopath/src/github.com/smancke/mailck/check.go:97 +0xcf
created by github.com/smancke/mailck.checkMailbox
        /home/travis/gopath/src/github.com/smancke/mailck/check.go:93 +0x315
```

**Comment by wunderkind2k1** [comment]
Hey Sebastian,

any ideas on that? We get this error on serveral email adresses.

Sven

**Comment by smancke** [comment]
@wunderkind2k1 I saw this error, but could not reproduce it. Maybe you can give me an mail address, where this occurs for you. Than I can further debug it.

**Comment by wunderkind2k1** [comment]
sure. E.g. you can try fortesque[at]web[dot]de - I can sent you others on a private channel if you want.

**Comment by smancke** [comment]
This address works for me.
Do you see the error constantly with some addresses, or is it sporadic?
If you want to give me adresses directly, you can use: sebastian -at- mancke -dot- net

**Comment by wunderkind2k1** [comment]
it crashes constantly. We use the library from within a webservice. I will double check it at home.

**Comment by bbuehrig** [comment]
I have tried the following code-snippet. Same error with 'go version go1.9 darwin/amd64'

```
package main

import (
	"fmt"

	"github.com/smancke/mailck"
)

func main() {
	result, _ := mailck.Check("noreply@mancke.net", "problematicemail@web.de")
	switch {

	case result.IsValid():
		// valid!
		fmt.Println("the mailserver accepts mails for this mailbox.")

	case result.IsError():
		// something went wrong in the smtp communication
		fmt.Println("we can't say for sure if the address is valid or not")

	case result.IsInvalid():
		fmt.Println("invalid for some reason")
		// the reason is contained in result.ResultDetail
		// or we can check for different reasons:
		switch result {
		case mailck.InvalidDomain:
			fmt.Println("domain is invalid")
		case mailck.InvalidSyntax:
			fmt.Println("e-mail address syntax is invalid")
		}
	}
}
```

I got this error:
```

```

**Comment by smancke** [comment]
@bbuehrig ok, thank's
With this, I can reproduce it from my local machine!
The check of `problematicemail@web.de` at my online service works fine: https://mailck.io/
(Seems, that web.de is closing the connection in a different way, if they think that the mailcheck is done from an invalid host.)

I will look into it now and do fix.

**Comment by smancke** [comment]
Please check the PR. If it works for you, I will merge it.

**Comment by wunderkind2k1** [comment]
Hey. Thx for the pr. But it still doesn't work:

goroutine 8 [running]:
net/smtp.(*Client).Close(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9/libexec/src/net/smtp/smtp.go:75 +0x22
panic(0x1147240, 0x123af20)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
net/smtp.(*Client).hello(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9/libexec/src/net/smtp/smtp.go:80 +0x26
net/smtp.(*Client).Quit(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9/libexec/src/net/smtp/smtp.go:382 +0x2f
panic(0x1147240, 0x123af20)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
net/smtp.(*Client).Hello(0x0, 0x1178111, 0xa, 0xa, 0x0)
	/usr/local/Cellar/go/1.9/libexec/src/net/smtp/smtp.go:96 +0x26
github.com/smancke/mailck.checkMailbox.func1(0x0, 0xc420010a20, 0x1178109, 0x12, 0xc42005e360, 0x11799b7, 0x17)
	/Users/sho/go/src/github.com/smancke/mailck/check.go:101 +0xcf
created by github.com/smancke/mailck.checkMailbox
	/Users/sho/go/src/github.com/smancke/mailck/check.go:97 +0x2fd

Does the code from @bbuehrig work for your locally?

**Comment by smancke** [comment]
Hi @wunderkind2k1 
yes, the code from @bbuehrig works for me.
The line numbers in you stack trace look the way, that you are still on the code before the fix,
please double check this. I have already merged the PR into the master, so you can simply use the master, now.

**Comment by wunderkind2k1** [comment]
will double check!

**Comment by bbuehrig** [comment]
In my environment it will work now. Thanks!

I will double check it with @wunderkind2k1 later the day.

**Comment by wunderkind2k1** [comment]
It works. I forgot the mandatory go get -u mailck. Thx for the patch. Keep up with your awesome work.

**Comment by smancke** [comment]
ok, great!
